version: '3'

services:
  jenkins:
    image: m3tr-jenkins
    user: root
    restart: unless-stopped
    environment:
      - TZ=Asia/Tehran
      - JAVA_OPTS=-Duser.timezone=Asia/Tehran
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - ./docker_certs_client:/certs/client
    ports:
      - "8080:8080"
      - "50000:50000"
    expose:
      - 2376
    labels:
      - "app.dws.name=jenkins"
      - "app.dws.part-of=jenkins"
      - "app.dws.created-by=M3tr"
    depends_on:
      - docker

  docker:
    image: m3tr-dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - ./docker_data:/var/lib/docker
      - ./docker_certs:/certs
      - ./docker_certs_client:/certs/client
      - ./jenkins_data:/var/jenkins_home
  gitea:
    image: gitea/gitea:1.21.2
    restart: unless-stopped
    environment:
      - TZ=Asia/Tehran
    volumes:
      - ./gitea_data:/data
    ports:
      - "3000:3000"
      - "2222:22"
    labels:
      - "app.dws.name=gitea"
      - "app.dws.part-of=jenkins"
      - "app.dws.created-by=M3tr"

volumes:
  jenkins_data: {}
  gitea_data: {}
  docker_certs_client: {}
  docker_certs: {}
  docker_data: {}

